# Generated by Django 3.2.7 on 2021-09-08 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Designation', models.CharField(default='', max_length=100)),
                ('From', models.CharField(default='', max_length=100)),
                ('To', models.CharField(default='', max_length=100)),
                ('Company', models.CharField(default='', max_length=100)),
                ('Street', models.CharField(default='', max_length=100)),
                ('Description', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
