# Generated by Django 3.2.7 on 2021-09-09 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0002_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('School', models.CharField(default='', max_length=100)),
                ('study', models.CharField(default='', max_length=100)),
                ('From', models.CharField(default='', max_length=100)),
                ('To', models.CharField(default='', max_length=100)),
                ('Icon', models.ImageField(default='', upload_to='Education')),
            ],
        ),
    ]
