# Generated by Django 3.2.7 on 2021-09-09 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0003_education'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='study',
        ),
    ]
