# Generated by Django 3.2.7 on 2021-09-09 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0004_remove_education_study'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='StudyArea',
            field=models.CharField(default='', max_length=100),
        ),
    ]
