# Generated by Django 3.2.7 on 2021-09-11 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0008_auto_20210911_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='langskill',
            name='str1',
            field=models.CharField(choices=[('Basic', 'Basic'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='langskill',
            name='str2',
            field=models.CharField(choices=[('Basic', 'Basic'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='langskill',
            name='str3',
            field=models.CharField(choices=[('Basic', 'Basic'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='', max_length=100),
        ),
    ]
