# Generated by Django 3.2.7 on 2021-09-12 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0010_portfolios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(default='', max_length=100)),
                ('designation', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
