# Generated by Django 3.2.7 on 2021-09-12 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0011_recommendations'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='', max_length=100)),
                ('skype', models.CharField(default='', max_length=100)),
                ('phone', models.CharField(default='', max_length=100)),
                ('github', models.CharField(default='', max_length=100)),
                ('linkedin', models.CharField(default='', max_length=100)),
                ('google_plus', models.CharField(default='', max_length=100)),
                ('youtube', models.CharField(default='', max_length=100)),
                ('website', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
