# Generated by Django 3.2.7 on 2021-09-12 16:53

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0013_remove_about_nationality'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='Nationality',
            field=django_countries.fields.CountryField(default='', max_length=746, multiple=True),
        ),
    ]
