# Generated by Django 3.2.7 on 2021-09-12 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0014_about_nationality'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='resume',
            field=models.FileField(default='', upload_to='Resume'),
        ),
        migrations.AlterField(
            model_name='about',
            name='Nationality',
            field=models.CharField(default='', max_length=100),
        ),
    ]
