# Generated by Django 3.2.9 on 2021-11-08 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0017_delete_user_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='userBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('heading', models.CharField(default='', max_length=100)),
                ('description', models.TextField(default='')),
            ],
        ),
    ]
