# Generated by Django 3.2.9 on 2021-11-09 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0018_userblog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='Birthday',
            field=models.DateField(default=''),
        ),
    ]
