# Generated by Django 3.2.9 on 2021-11-09 11:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0019_alter_about_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='Birthday',
            field=models.DateField(verbose_name=datetime.date),
        ),
    ]
