# Generated by Django 3.2.9 on 2021-11-10 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0020_alter_about_birthday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userblog',
            name='description',
        ),
        migrations.AlterField(
            model_name='about',
            name='Birthday',
            field=models.DateField(default=''),
        ),
    ]
