# Generated by Django 3.2.9 on 2021-11-10 11:19

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0021_auto_20211110_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='userblog',
            name='description',
            field=ckeditor.fields.RichTextField(default=''),
        ),
    ]
