# Generated by Django 3.2.9 on 2021-11-10 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0026_alter_userblog_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='userblog',
            name='Icon',
            field=models.ImageField(default='', upload_to='Blog/Icons'),
        ),
    ]
