# Generated by Django 3.2.9 on 2021-11-11 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0027_userblog_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userblog',
            name='Icon',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
