# Generated by Django 3.2.9 on 2021-11-11 09:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0029_alter_userblog_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userblog',
            name='Icon',
            field=models.DateField(default=datetime.datetime(2021, 11, 11, 14, 22, 1, 812414)),
        ),
    ]
