# Generated by Django 3.2.9 on 2021-11-11 09:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0030_alter_userblog_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='userblog',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2021, 11, 11, 14, 23, 34, 399085)),
        ),
        migrations.AlterField(
            model_name='userblog',
            name='Icon',
            field=models.ImageField(default='', upload_to='Blog/Icons'),
        ),
    ]
