# Generated by Django 3.2.9 on 2021-11-11 09:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0031_auto_20211111_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userblog',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2021, 11, 11, 14, 30, 3, 329678)),
        ),
    ]
