# Generated by Django 3.2.9 on 2021-11-11 09:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0032_alter_userblog_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userblog',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2021, 11, 11, 14, 33, 7, 517831)),
        ),
    ]
