# Generated by Django 3.2.9 on 2021-11-11 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0033_alter_userblog_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userblog',
            name='created_at',
        ),
    ]
