# Generated by Django 3.2.9 on 2021-11-11 10:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0034_remove_userblog_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userblog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 11, 10, 12, 5, 774326, tzinfo=utc)),
        ),
    ]
