# Generated by Django 3.2.9 on 2021-11-12 11:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0038_auto_20211112_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='userblog',
            name='quote',
            field=models.CharField(default='', max_length=3000),
        ),
        migrations.AddField(
            model_name='userblog',
            name='tags',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='userblog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 12, 11, 23, 33, 197660, tzinfo=utc)),
        ),
    ]
