# Generated by Django 3.2.9 on 2021-11-12 11:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0039_auto_20211112_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userblog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 12, 11, 39, 49, 476424, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userblog',
            name='quote',
            field=models.CharField(default='', max_length=3000, null=True),
        ),
    ]
